const workCards = [
  {
    title: "albañileria",
    user: "pepito",
    id: 1,
    created_at: "diayfecha",
    category: "albañileria",
    base_price: "2000",
  },
  {
    title: "electicidad",
    user: "pepito",
    id: 2,
    created_at: "diayfecha",
    category: "electicidad",
    base_price: "2000",
  },
  {
    title: "plomeria",
    user: "pepito",
    id: 3,
    created_at: "diayfecha",
    category: "plomeria",
    base_price: "2000",
  },
  {
    title: "techo",
    user: "pepito",
    id: 4,
    created_at: "diayfecha",
    category: "techo",
    base_price: "2000",
  },
  {
    title: "colocacion",
    user: "pepito",
    id: 6,
    created_at: "diayfecha",
    category: "colocacion",
    base_price: "2000",
  },
  {
    title: "colocacion",
    user: "pepito",
    id: 7,
    created_at: "diayfecha",
    category: "colocacion",
    base_price: "2000",
  },
  {
    title: "colocacion",
    user: "pepito",
    id: 8,
    created_at: "diayfecha",
    category: "colocacion",
    base_price: "2000",
  },
  {
    title: "colocacion",
    user: "pepito",
    id: 9,
    created_at: "diayfecha",
    category: "colocacion",
    base_price: "2000",
  },
  {
    title: "colocacion",
    user: "pepito",
    id: 10,
    created_at: "diayfecha",
    category: "colocacion",
    base_price: "2000",
  },
  {
    title: "colocacion",
    user: "pepito",
    id: 11,
    created_at: "diayfecha",
    category: "colocacion",
    base_price: "2000",
  },
  {
    title: "colocacion",
    user: "pepito",
    id: 12,
    created_at: "diayfecha",
    category: "colocacion",
    base_price: "2000",
  },
  {
    title: "colocacion",
    user: "pepito",
    id: 13,
    created_at: "diayfecha",
    category: "colocacion",
    base_price: "2000",
  },
];
export default workCards;
